name: 'Profile Readme Development Stats'
author: Anmol Pratap Singh
description: 'Are you an early 🐤 or a night 🦉? When are you most productive during the day? Let''s check out in your readme!'

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run WakaTime Readme Stats
        uses: wakareadmestats/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: "waka"
          PULL_BRANCH_NAME: ""
          PUSH_BRANCH_NAME: ""
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "Updated with Dev Metrics"
          COMMIT_USERNAME: ""
          COMMIT_EMAIL: ""
          COMMIT_SINGLE: "False"
          LOCALE: "en"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          IGNORED_REPOS: ""
          SYMBOL_VERSION: "1"
          DEBUG_LOGGING: ${{ runner.debug }}
